### ISSUE TITLE
Unable to authenticate google drive account 

### ISSUE THREAD

**Issue by capriciousduck** [cloud-transfer/cloud-transfer-backend#10]
I have set up everything and deployed the app on my heroku account, but I am not able to authenticate my google drive. Should I change heroku config vars ? Please help.

**Comment by dhaval-mehta** [comment]
you need to obtain client id, client secret for google drive api from [here](https://console.cloud.google.com/apis/api/drive.googleapis.com/overview). 

you also need to set redirect uri in google console. set it to "{base_url}/api/oauth/google/redirect". base url is hostname of your website.

after obtaining client id and secret, set following env variables.

1. client_id
2. client_secret
3. redirect_uri

after that your app will be ready to use.

**Comment by capriciousduck** [comment]
using this ---> {base_url}/api/oauth/google/redirect  causes login loop instead the url should be 

{base_url}/api/oauth/google/callback

**Comment by dhaval-mehta** [comment]
{base_url}/api/oauth/google/redirect  -> redirect users for google authentication
{base_url}/api/oauth/google/callback -> after authentication google call this url with code which further used to generate token.

I think your redirect uri is not set properly.

**Comment by capriciousduck** [comment]
{base_url}/api/oauth/google/callback

the above url worked for me

**Comment by capriciousduck** [comment]
the graddle app is not working on heroku. Please fix.

**Comment by noweir** [comment]
i need to know where can i put my clint id and data
