### ISSUE TITLE
latest release on heroku

### ISSUE THREAD

**Issue by capriciousduck** [cloud-transfer/cloud-transfer-backend#11]
deploy  of latest release 2.0 fails on heroku. Please help.

**Comment by capriciousduck** [comment]
here are the logs

-----> Gradle app detected
-----> Spring Boot detected
-----> Installing JDK 1.8... done
-----> Building Gradle app...
-----> executing ./gradlew build -x test
       Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip
       .................................................................................
       
       Welcome to Gradle 5.0!
       
       Here are the highlights of this release:
        - Kotlin DSL 1.0
        - Task timeouts
        - Dependency alignment aka BOM support
        - Interactive `gradle init`
       
       For more details see https://docs.gradle.org/5.0/release-notes.html
       
       > Task :compileJava FAILED
       
       FAILURE: Build failed with an exception.
       
       * What went wrong:
       Execution failed for task ':compileJava'.
       > Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.
       
       * Try:
       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
       
       * Get more help at https://help.gradle.org
       
       BUILD FAILED in 25s
       1 actionable task: 1 executed
 !     ERROR: Failed to run Gradle!
       We're sorry this build is failing. If you can't find the issue in application
       code, please submit a ticket so we can help: https://help.heroku.com
       You can also try reverting to the previous version of the buildpack by running:
       $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-gradle#previous-version
       
       Thanks,
       Heroku
 !     Push rejected, failed to compile Gradle app.
 !     Push failed

**Comment by dhaval-mehta** [comment]
you are using branch 2.0.0.RELESE which is not configured to run on heroku as well as it is under development. 
I request you to use master branch for your personal use.

**Comment by capriciousduck** [comment]
Okay. Actually the master branch is working fine. But the upload speed is limited to 2.0MBps. How to increase the upload speed?

**Comment by dhaval-mehta** [comment]
You have raised a issue here: https://github.com/cloud-transfer/cloud-transfer-backend/issues/11
let's discuss it there.
