### ISSUE TITLE
Upload Speed Limit

### ISSUE THREAD

**Issue by capriciousduck** [cloud-transfer/cloud-transfer-backend#12]
Is the upload speed limited ? It has max upload speed of 2MBps.

**Comment by dhaval-mehta** [comment]
there is no limit from my side. speed depends upon connectivity between heroku server and file provider server and heroku server and google server.

**Comment by dhaval-mehta** [comment]
try to upload this link: http://ipv4.download.thinkbroadband.com:8080/512MB.zip
this gives me 4-4.5 MB/s speed

**Comment by capriciousduck** [comment]
And how to cancel the upload?

**Comment by capriciousduck** [comment]
Are the files first downloaded to heroku and then uploaded ? or are they transfered directly without downloading to heroku?

**Comment by dhaval-mehta** [comment]
This feature is under development in 2.0 release
meanwhile only one solution is let upload to finish then delete it from google drive.

**Comment by capriciousduck** [comment]
Also the sign in info is not saved, the app asks often when re-visited

**Comment by dhaval-mehta** [comment]
first file is downloaded in heroku then it is uploaded to google drive.

**Comment by capriciousduck** [comment]
will you alert me when 2.0 is completed ?

**Comment by dhaval-mehta** [comment]
> Also the sign in info is not saved, the app asks often when re-visited

I didn't get you.

**Comment by capriciousduck** [comment]
Okay, please alert me when 2.0 is completed.

**Comment by dhaval-mehta** [comment]
for speed limit issue, my suggestion is to use google cloud. 
I think connectivity of heroku server with google drive is actual bottleneck.
