### ISSUE TITLE
google cloud

### ISSUE THREAD

**Issue by capriciousduck** [cloud-transfer/cloud-transfer-backend#13]
How can I deploy the master branch on google cloud? Any instructions?

**Comment by capriciousduck** [comment]
Should I use google vps or app engine?

**Comment by dhaval-mehta** [comment]
I have not used it. This is my guess that you will get high speed in google cloud.
2.0 release will use docker for deployment. 
Just you need to figure it out how to use docker on google cloud for deployment.

for master branch
download code and set port to 80. if you don't know how to set port [read this](https://stackoverflow.com/questions/21083170/how-to-configure-port-for-a-spring-boot-application)
1. install java 8 or 11 and make sure that java home is set,
2. install maven
3. set env variables
4. run ./mvnw spring-boot:run
