### ISSUE TITLE
Invalid error

### ISSUE THREAD

**Issue by khusnan21** [cloud-transfer/cloud-transfer-backend#7]
How to solved invalid error?
Ho to intergrate googleapis to thisnsite?

https://url-2-gdrive.herokuapp.com

**Comment by capriciousduck** [comment]
Hi, I have set up everything and deployed the app on my heroku account, but I am not able to authenticate my google drive. Should I change heroku config vars ? Please help.

**Comment by dhaval-mehta** [comment]
please read my comment for: https://github.com/dhaval-mehta/url-to-google-drive/issues/10
